
flat_file <- structure(
  list(
    MetaData = list(
      `Data Type` = character(),
      `Data Version` = character(),
      `Security Classification` = character(),
      `1a Program Name` = character(),
      `1b Program Phase/Milestone` = character(),
      `2 Prime Mission Product` = character(),
      `3 Reporting Organization Type` = character(),
      `4a Organization Address City` = character(),
      `4a Organization Address Line 1` = character(),
      `4a Organization Address Line 2` = character(),
      `4a Organization Address State` = character(),
      `4a Organization Address Zip` = character(),
      `4a Organization Name` = character(),
      `4b Division Address City` = character(),
      `4b Division Address Line 1` = character(),
      `4b Division Address Line 2` = character(),
      `4b Division Address State` = character(),
      `4b Division Address Zip` = character(),
      `4b Division Name` = character(),
      `5 Approved Plan Number` = character(),
      `6 Customer` = character(),
      `7 Contract Type` = character(),
      `8 Contract Price` = numeric(),
      `9 Contract Ceiling` = numeric(),
      `10a Contract No` = character(),
      `10b Latest Modification` = character(),
      `10c Solicitation No` = character(),
      `10d Name` = character(),
      `10e Order/Lot No` = character(),
      `11a PoP Start Date` =  lubridate::ymd(),
      `11b PoP End Date` = lubridate::ymd(),
      `12 Appropriation` = character(),
      `13 Report Cycle` = character(),
      `14 Submission Number` = integer(),
      `15 Resubmission Number` = integer(),
      `16 Report As Of` = lubridate::ymd(),
      `17 Name` = character(),
      `18 Department` = character(),
      `19 Telephone Number` = character(),
      `20 Email Address` = character(),
      `21 Date Prepared` = lubridate::ymd(),
      `Subtotal TD` = numeric(),
      `Subtotal AC` = numeric(),
      `G&A TD` = numeric(),
      `G&A AC` = numeric(),
      `UB AC` = numeric(),
      `MR AC` = numeric(),
      `FCCM TD` = numeric(),
      `FCCM AC` = numeric(),
      `Fee TD` = numeric(),
      `Fee AC` = numeric(),
      `Price TD` = numeric(),
      `Price AC` = numeric(),
      `DD 1921 Remarks` = character()
    ),
    Data = tibble::tibble(
      address = character(),
      WBSElementID = factor(),
      WBSElementName = factor(),
      UnitOfMeasure = factor(
        levels = c("Dollars",
                   "Hours",
                   "Units")),
      Recurring_Nonrecurring = factor(
        levels = c("Nonrecurring",
                   "Recurring")),
      ToDate_AtCompletion = factor(
        levels = c("ToDate",
                   "AtCompletion")),
      Value = numeric(),
      WBSElementRemarks = character(),
      FullName = character(),
    ),
    Definitions = tibble::tribble(
      ~`Column Letter`,             ~`Column Label`,                                                                      ~`Full Name`, ~`1921 Location`,  ~`1921-1 Location`, ~`Unit of Measure`, ~`To Date / \r\nAt Completion`, ~`Recurring / Nonrecurring`,       ~`Functional Category`,                 ~`Functional Element`,
      "D",                "WBS Code",                                                                      "WBS Code",       "Column A",           "Item 18",            "N/A",                      "N/A",                       "N/A",                      "N/A",                               "N/A",
      "E",  "WBS Reporting Elements",                                                        "WBS Reporting Elements",       "Column B",           "Item 19",            "N/A",                      "N/A",                       "N/A",                      "N/A",                               "N/A",
      "F",                "Units TD",                                                       "Number of Units To Date",       "Column C",          "Item 20a",          "Units",                  "To Date",                 "Recurring",                      "N/A",                               "N/A",
      "G",                 "NR $ TD",                                           "Nonrecurring Costs Incurred To Date",       "Column D", "Line 21, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                      "N/A",                               "N/A",
      "H",                "Rec $ TD",                                              "Recurring Costs Incurred To Date",       "Column E", "Line 21, Column B",        "Dollars",                  "To Date",                 "Recurring",                      "N/A",                               "N/A",
      "I",                "Units AC",                                                 "Number of Units At Completion",       "Column G",          "Item 20b",          "Units",            "At Completion",                 "Recurring",                      "N/A",                               "N/A",
      "J",                 "NR $ AC",                                     "Nonrecurring Costs Incurred At Completion",       "Column H", "Line 21, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                      "N/A",                               "N/A",
      "K",                "Rec $ AC",                                        "Recurring Costs Incurred At Completion",       "Column I", "Line 21, Column E",        "Dollars",            "At Completion",                 "Recurring",                      "N/A",                               "N/A",
      "L",           "NR Eng Hrs TD",                  "Nonrecurring Direct Engineering Labor Hours Incurred To Date",            "N/A",  "Line 1, Column A",          "Hours",                  "To Date",              "Nonrecurring",              "Engineering",          "Direct Engineering Labor",
      "M",          "Rec Eng Hrs TD",                     "Recurring Direct Engineering Labor Hours Incurred To Date",            "N/A",  "Line 1, Column B",          "Hours",                  "To Date",                 "Recurring",              "Engineering",          "Direct Engineering Labor",
      "N",           "NR Eng Hrs AC",            "Nonrecurring Direct Engineering Labor Hours Incurred At Completion",            "N/A",  "Line 1, Column D",          "Hours",            "At Completion",              "Nonrecurring",              "Engineering",          "Direct Engineering Labor",
      "O",          "Rec Eng Hrs AC",               "Recurring Direct Engineering Labor Hours Incurred At Completion",            "N/A",  "Line 1, Column E",          "Hours",            "At Completion",                 "Recurring",              "Engineering",          "Direct Engineering Labor",
      "P",      "NR Direct Eng $ TD",                "Nonrecurring Direct Engineering Labor Dollars Incurred To Date",            "N/A",  "Line 2, Column A",        "Dollars",                  "To Date",              "Nonrecurring",              "Engineering",          "Direct Engineering Labor",
      "Q",     "Rec Direct Eng $ TD",                   "Recurring Direct Engineering Labor Dollars Incurred To Date",            "N/A",  "Line 2, Column B",        "Dollars",                  "To Date",                 "Recurring",              "Engineering",          "Direct Engineering Labor",
      "R",      "NR Direct Eng $ AC",          "Nonrecurring Direct Engineering Labor Dollars Incurred At Completion",            "N/A",  "Line 2, Column D",        "Dollars",            "At Completion",              "Nonrecurring",              "Engineering",          "Direct Engineering Labor",
      "S",     "Rec Direct Eng $ AC",             "Recurring Direct Engineering Labor Dollars Incurred At Completion",            "N/A",  "Line 2, Column E",        "Dollars",            "At Completion",                 "Recurring",              "Engineering",          "Direct Engineering Labor",
      "T",          "NR Eng OH $ TD",                    "Nonrecurring Engineering Overhead Dollars Incurred To Date",            "N/A",  "Line 3, Column A",        "Dollars",                  "To Date",              "Nonrecurring",              "Engineering",              "Engineering Overhead",
      "U",         "Rec Eng OH $ TD",                       "Recurring Engineering Overhead Dollars Incurred To Date",            "N/A",  "Line 3, Column B",        "Dollars",                  "To Date",                 "Recurring",              "Engineering",              "Engineering Overhead",
      "V",          "NR Eng OH $ AC",              "Nonrecurring Engineering Overhead Dollars Incurred At Completion",            "N/A",  "Line 3, Column D",        "Dollars",            "At Completion",              "Nonrecurring",              "Engineering",              "Engineering Overhead",
      "W",         "Rec Eng OH $ AC",                 "Recurring Engineering Overhead Dollars Incurred At Completion",            "N/A",  "Line 3, Column E",        "Dollars",            "At Completion",                 "Recurring",              "Engineering",              "Engineering Overhead",
      "X",          "NR Tool Hrs TD",                      "Nonrecurring Direct Tooling Labor Hours Incurred To Date",            "N/A",  "Line 5, Column A",          "Hours",                  "To Date",              "Nonrecurring",                  "Tooling",              "Direct Tooling Labor",
      "Y",         "Rec Tool Hrs TD",                         "Recurring Direct Tooling Labor Hours Incurred To Date",            "N/A",  "Line 5, Column B",          "Hours",                  "To Date",                 "Recurring",                  "Tooling",              "Direct Tooling Labor",
      "Z",          "NR Tool Hrs AC",                "Nonrecurring Direct Tooling Labor Hours Incurred At Completion",            "N/A",  "Line 5, Column D",          "Hours",            "At Completion",              "Nonrecurring",                  "Tooling",              "Direct Tooling Labor",
      "AA",         "Rec Tool Hrs AC",                   "Recurring Direct Tooling Labor Hours Incurred At Completion",            "N/A",  "Line 5, Column E",          "Hours",            "At Completion",                 "Recurring",                  "Tooling",              "Direct Tooling Labor",
      "AB",     "NR Tool Direct $ TD",                    "Nonrecurring Direct Tooling Labor Dollars Incurred To Date",            "N/A",  "Line 6, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                  "Tooling",              "Direct Tooling Labor",
      "AC",    "Rec Tool Direct $ TD",                       "Recurring Direct Tooling Labor Dollars Incurred To Date",            "N/A",  "Line 6, Column B",        "Dollars",                  "To Date",                 "Recurring",                  "Tooling",              "Direct Tooling Labor",
      "AD",     "NR Tool Direct $ AC",              "Nonrecurring Direct Tooling Labor Dollars Incurred At Completion",            "N/A",  "Line 6, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                  "Tooling",              "Direct Tooling Labor",
      "AE",    "Rec Tool Direct $ AC",                 "Recurring Direct Tooling Labor Dollars Incurred At Completion",            "N/A",  "Line 6, Column E",        "Dollars",            "At Completion",                 "Recurring",                  "Tooling",              "Direct Tooling Labor",
      "AF",      "NR Tool/Equip $ TD",              "Nonrecurring Direct Tooling & Equipment Dollars Incurred To Date",            "N/A",  "Line 7, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                  "Tooling",        "Direct Tooling & Equipment",
      "AG",     "Rec Tool/Equip $ TD",                 "Recurring Direct Tooling & Equipment Dollars Incurred To Date",            "N/A",  "Line 7, Column B",        "Dollars",                  "To Date",                 "Recurring",                  "Tooling",        "Direct Tooling & Equipment",
      "AH",      "NR Tool/Equip $ AC",        "Nonrecurring Direct Tooling & Equipment Dollars Incurred At Completion",            "N/A",  "Line 7, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                  "Tooling",        "Direct Tooling & Equipment",
      "AI",     "Rec Tool/Equip $ AC",           "Recurring Direct Tooling & Equipment Dollars Incurred At Completion",            "N/A",  "Line 7, Column E",        "Dollars",            "At Completion",                 "Recurring",                  "Tooling",        "Direct Tooling & Equipment",
      "AJ",            "NR QC Hrs TD",              "Nonrecurring Direct Quality Control Labor Hours Incurred To Date",            "N/A",  "Line 8, Column A",          "Hours",                  "To Date",              "Nonrecurring",          "Quality Control",      "Direct Quality Control Labor",
      "AK",           "Rec QC Hrs TD",                 "Recurring Direct Quality Control Labor Hours Incurred To Date",            "N/A",  "Line 8, Column B",          "Hours",                  "To Date",                 "Recurring",          "Quality Control",      "Direct Quality Control Labor",
      "AL",            "NR QC Hrs AC",        "Nonrecurring Direct Quality Control Labor Hours Incurred At Completion",            "N/A",  "Line 8, Column D",          "Hours",            "At Completion",              "Nonrecurring",          "Quality Control",      "Direct Quality Control Labor",
      "AM",           "Rec QC Hrs AC",           "Recurring Direct Quality Control Labor Hours Incurred At Completion",            "N/A",  "Line 8, Column E",          "Hours",            "At Completion",                 "Recurring",          "Quality Control",      "Direct Quality Control Labor",
      "AN",       "NR QC Direct $ TD",            "Nonrecurring Direct Quality Control Labor Dollars Incurred To Date",            "N/A",  "Line 9, Column A",        "Dollars",                  "To Date",              "Nonrecurring",          "Quality Control",      "Direct Quality Control Labor",
      "AO",      "Rec QC Direct $ TD",               "Recurring Direct Quality Control Labor Dollars Incurred To Date",            "N/A",  "Line 9, Column B",        "Dollars",                  "To Date",                 "Recurring",          "Quality Control",      "Direct Quality Control Labor",
      "AP",       "NR QC Direct $ AC",      "Nonrecurring Direct Quality Control Labor Dollars Incurred At Completion",            "N/A",  "Line 9, Column D",        "Dollars",            "At Completion",              "Nonrecurring",          "Quality Control",      "Direct Quality Control Labor",
      "AQ",      "Rec QC Direct $ AC",         "Recurring Direct Quality Control Labor Dollars Incurred At Completion",            "N/A",  "Line 9, Column E",        "Dollars",            "At Completion",                 "Recurring",          "Quality Control",      "Direct Quality Control Labor",
      "AR",           "NR MFG Hrs TD",                "Nonrecurring Direct Manufacturing Labor Hours Incurred To Date",            "N/A", "Line 10, Column A",          "Hours",                  "To Date",              "Nonrecurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AS",          "Rec MFG Hrs TD",                   "Recurring Direct Manufacturing Labor Hours Incurred To Date",            "N/A", "Line 10, Column B",          "Hours",                  "To Date",                 "Recurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AT",           "NR MFG Hrs AC",          "Nonrecurring Direct Manufacturing Labor Hours Incurred At Completion",            "N/A", "Line 10, Column D",          "Hours",            "At Completion",              "Nonrecurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AU",          "Rec MFG Hrs AC",             "Recurring Direct Manufacturing Labor Hours Incurred At Completion",            "N/A", "Line 10, Column E",          "Hours",            "At Completion",                 "Recurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AV",      "NR MFG Direct $ TD",              "Nonrecurring Direct Manufacturing Labor Dollars Incurred To Date",            "N/A", "Line 11, Column A",        "Dollars",                  "To Date",              "Nonrecurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AW",     "Rec MFG Direct $ TD",                 "Recurring Direct Manufacturing Labor Dollars Incurred To Date",            "N/A", "Line 11, Column B",        "Dollars",                  "To Date",                 "Recurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AX",      "NR MFG Direct $ AC",        "Nonrecurring Direct Manufacturing Labor Dollars Incurred At Completion",            "N/A", "Line 11, Column D",        "Dollars",            "At Completion",              "Nonrecurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AY",     "Rec MFG Direct $ AC",           "Recurring Direct Manufacturing Labor Dollars Incurred At Completion",            "N/A", "Line 11, Column E",        "Dollars",            "At Completion",                 "Recurring",            "Manufacturing",        "Direct Manufacturing Labor",
      "AZ",      "NR MFG Ops OH $ TD",       "Nonrecurring Manufacturing Operations Overhead Dollars Incurred To Date",            "N/A", "Line 12, Column A",        "Dollars",                  "To Date",              "Nonrecurring", "Manufacturing Operations", "Manufacturing Operations Overhead",
      "BA",     "Rec MFG Ops OH $ TD",          "Recurring Manufacturing Operations Overhead Dollars Incurred To Date",            "N/A", "Line 12, Column B",        "Dollars",                  "To Date",                 "Recurring", "Manufacturing Operations", "Manufacturing Operations Overhead",
      "BB",      "NR MFG Ops OH $ AC", "Nonrecurring Manufacturing Operations Overhead Dollars Incurred At Completion",            "N/A", "Line 12, Column D",        "Dollars",            "At Completion",              "Nonrecurring", "Manufacturing Operations", "Manufacturing Operations Overhead",
      "BC",     "Rec MFG Ops OH $ AC",    "Recurring Manufacturing Operations Overhead Dollars Incurred At Completion",            "N/A", "Line 12, Column E",        "Dollars",            "At Completion",                 "Recurring", "Manufacturing Operations", "Manufacturing Operations Overhead",
      "BD",         "NR Raw Mat $ TD",                            "Nonrecurring Raw Material Dollars Incurred To Date",            "N/A", "Line 14, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                 "Material",                      "Raw Material",
      "BE",        "Rec Raw Mat $ TD",                               "Recurring Raw Material Dollars Incurred To Date",            "N/A", "Line 14, Column B",        "Dollars",                  "To Date",                 "Recurring",                 "Material",                      "Raw Material",
      "BF",         "NR Raw Mat $ AC",                      "Nonrecurring Raw Material Dollars Incurred At Completion",            "N/A", "Line 14, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                 "Material",                      "Raw Material",
      "BG",        "Rec Raw Mat $ AC",                         "Recurring Raw Material Dollars Incurred At Completion",            "N/A", "Line 14, Column E",        "Dollars",            "At Completion",                 "Recurring",                 "Material",                      "Raw Material",
      "BH",     "NR Purch Parts $ TD",                         "Nonrecurring Purchased Parts Dollars Incurred To Date",            "N/A", "Line 15, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                 "Material",                   "Purchased Parts",
      "BI",    "Rec Purch Parts $ TD",                            "Recurring Purchased Parts Dollars Incurred To Date",            "N/A", "Line 15, Column B",        "Dollars",                  "To Date",                 "Recurring",                 "Material",                   "Purchased Parts",
      "BJ",     "NR Purch Parts $ AC",                   "Nonrecurring Purchased Parts Dollars Incurred At Completion",            "N/A", "Line 15, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                 "Material",                   "Purchased Parts",
      "BK",    "Rec Purch Parts $ AC",                      "Recurring Purchased Parts Dollars Incurred At Completion",            "N/A", "Line 15, Column E",        "Dollars",            "At Completion",                 "Recurring",                 "Material",                   "Purchased Parts",
      "BL",     "NR Purch Equip $ TD",                     "Nonrecurring Purchased Equipment Dollars Incurred To Date",            "N/A", "Line 16, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                 "Material",               "Purchased Equipment",
      "BM",    "Rec Purch Equip $ TD",                        "Recurring Purchased Equipment Dollars Incurred To Date",            "N/A", "Line 16, Column B",        "Dollars",                  "To Date",                 "Recurring",                 "Material",               "Purchased Equipment",
      "BN",     "NR Purch Equip $ AC",               "Nonrecurring Purchased Equipment Dollars Incurred At Completion",            "N/A", "Line 16, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                 "Material",               "Purchased Equipment",
      "BO",    "Rec Purch Equip $ AC",                  "Recurring Purchased Equipment Dollars Incurred At Completion",            "N/A", "Line 16, Column E",        "Dollars",            "At Completion",                 "Recurring",                 "Material",               "Purchased Equipment",
      "BP",          "NR Mat OH $ TD",              "Nonrecurring Material Handling/Overhead Dollars Incurred To Date",            "N/A", "Line 17, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                 "Material",        "Material Handling/Overhead",
      "BQ",         "Rec Mat OH $ TD",                 "Recurring Material Handling/Overhead Dollars Incurred To Date",            "N/A", "Line 17, Column B",        "Dollars",                  "To Date",                 "Recurring",                 "Material",        "Material Handling/Overhead",
      "BR",          "NR Mat OH $ AC",        "Nonrecurring Material Handling/Overhead Dollars Incurred At Completion",            "N/A", "Line 17, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                 "Material",        "Material Handling/Overhead",
      "BS",         "Rec Mat OH $ AC",           "Recurring Material Handling/Overhead Dollars Incurred At Completion",            "N/A", "Line 17, Column E",        "Dollars",            "At Completion",                 "Recurring",                 "Material",        "Material Handling/Overhead",
      "BT",  "NR Direct Rep Sub $ TD",          "Nonrecurring Direct-Reporting Subcontractor Dollars Incurred To Date",            "N/A", "Line 18, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                 "Material",    "Direct-Reporting Subcontractor",
      "BU", "Rec Direct Rep Sub $ TD",             "Recurring Direct-Reporting Subcontractor Dollars Incurred To Date",            "N/A", "Line 18, Column B",        "Dollars",                  "To Date",                 "Recurring",                 "Material",    "Direct-Reporting Subcontractor",
      "BV",  "NR Direct Rep Sub $ AC",    "Nonrecurring Direct-Reporting Subcontractor Dollars Incurred At Completion",            "N/A", "Line 18, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                 "Material",    "Direct-Reporting Subcontractor",
      "BW", "Rec Direct Rep Sub $ AC",       "Recurring Direct-Reporting Subcontractor Dollars Incurred At Completion",            "N/A", "Line 18, Column E",        "Dollars",            "At Completion",                 "Recurring",                 "Material",    "Direct-Reporting Subcontractor",
      "BX",           "NR Other $ TD",                 "Nonrecurring Other Costs Not Shown Elsewhere Incurred To Date",            "N/A", "Line 20, Column A",        "Dollars",                  "To Date",              "Nonrecurring",                    "Other",   "Other Costs Not Shown Elsewhere",
      "BY",          "Rec Other $ TD",                    "Recurring Other Costs Not Shown Elsewhere Incurred To Date",            "N/A", "Line 20, Column B",        "Dollars",                  "To Date",                 "Recurring",                    "Other",   "Other Costs Not Shown Elsewhere",
      "BZ",           "NR Other $ AC",           "Nonrecurring Other Costs Not Shown Elsewhere Incurred At Completion",            "N/A", "Line 20, Column D",        "Dollars",            "At Completion",              "Nonrecurring",                    "Other",   "Other Costs Not Shown Elsewhere",
      "CA",          "Rec Other $ AC",              "Recurring Other Costs Not Shown Elsewhere Incurred At Completion",            "N/A", "Line 20, Column E",        "Dollars",            "At Completion",                 "Recurring",                    "Other",   "Other Costs Not Shown Elsewhere",
      "CB",                 "Remarks",                                                                       "Remarks",            "N/A",           "Item 22",            "N/A",                      "N/A",                       "N/A",                      "N/A",                               "N/A"
    ) %>% dplyr::mutate_all(stringr::str_replace_all, "N/A", NA_character_) %>% 
      dplyr::rename(
        ColumnLetter = `Column Letter`,
        ColumnLabel = `Column Label`,
        FullName = `Full Name`,
        CDSRLocation = `1921 Location`,
        FCHRLocation = `1921-1 Location`,
        UnitOfMeasure = `Unit of Measure`,
        ToDate_AtCompletion = `To Date / \r\nAt Completion`,
        Recurring_Nonrecurring = `Recurring / Nonrecurring`,
        FunctionalCategory = `Functional Category`,
        FunctionalElement = `Functional Element`
      )
  ),
  class = "flat_file"
)

new_flat_file <- function(...) {
  structure(flat_file, class = "flat_file")
}
