
flat_file <- structure(
  list(
    MetaData = list(
      `Data Type` = character(),
      `Data Version` = character(),
      `Security Classification` = character(),
      `1a Program Name` = character(),
      `1b Program Phase/Milestone` = character(),
      `2 Prime Mission Product` = character(),
      `3 Reporting Organization Type` = character(),
      `4a Organization Address City` = character(),
      `4a Organization Address Line 1` = character(),
      `4a Organization Address Line 2` = character(),
      `4a Organization Address State` = character(),
      `4a Organization Address Zip` = character(),
      `4a Organization Name` = character(),
      `4b Division Address City` = character(),
      `4b Division Address Line 1` = character(),
      `4b Division Address Line 2` = character(),
      `4b Division Address State` = character(),
      `4b Division Address Zip` = character(),
      `4b Division Name` = character(),
      `5 Approved Plan Number` = character(),
      `6 Customer` = character(),
      `7 Contract Type` = character(),
      `8 Contract Price` = numeric(),
      `9 Contract Ceiling` = numeric(),
      `10a Contract No` = character(),
      `10b Latest Modification` = character(),
      `10c Solicitation No` = character(),
      `10d Name` = character(),
      `10e Order/Lot No` = character(),
      `11a PoP Start Date` =  lubridate::ymd(),
      `11b PoP End Date` = lubridate::ymd(),
      `12 Appropriation` = character(),
      `13 Report Cycle` = character(),
      `14 Submission Number` = integer(),
      `15 Resubmission Number` = integer(),
      `16 Report As Of` = lubridate::ymd(),
      `17 Name` = character(),
      `18 Department` = character(),
      `19 Telephone Number` = character(),
      `20 Email Address` = character(),
      `21 Date Prepared` = lubridate::ymd(),
      `Subtotal TD` = numeric(),
      `Subtotal AC` = numeric(),
      `G&A TD` = numeric(),
      `G&A AC` = numeric(),
      `UB AC` = numeric(),
      `MR AC` = numeric(),
      `FCCM TD` = numeric(),
      `FCCM AC` = numeric(),
      `Fee TD` = numeric(),
      `Fee AC` = numeric(),
      `Price TD` = numeric(),
      `Price AC` = numeric(),
      `DD 1921 Remarks` = character()
    ),
    Data = tibble::tibble(
      address = character(),
      WBSElementID = factor(),
      WBSElementName = factor(),
      UnitOfMeasure = factor(
        levels = c("Dollars",
                   "Hours",
                   "Units")),
      Recurring_Nonrecurring = factor(
        levels = c("Nonrecurring",
                   "Recurring")),
      ToDate_AtCompletion = factor(
        levels = c("ToDate",
                   "AtCompletion")),
      Value = numeric(),
      WBSElementRemarks = character(),
      FullName = character(),
    ),
    Definitions = tibble::tibble(
      ColumnLetter = character(),
      ColumnLabel = character(),
      FullName = character(),
      CDSRLocation = character(),
      FCHRLocation = character(),
      UnitOfMeasure = character(),
      ToDate_AtCompletion = character(),
      Recurring_Nonrecurring = character(),
      FunctionalCategory = character(),
      FunctionalElement = character()
    )
  ),
  class = "flat_file"
)

new_flat_file <- function(...) {
  structure(flat_file, class = "flat_file")
}
